name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install wait-on globally
        run: npm install -g wait-on

      - name: Start server
        run: npm start &
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_DATABASE: sakila
          DB_PORT: 3306
          SESSION_SECRET: test-secret-key

      - name: Wait for server to be ready
        run: wait-on http://localhost:3000 --timeout 60000

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          CYPRESS_STAFF_EMAIL: Mike.Hillyer@sakilastaff.com
          CYPRESS_STAFF_PASSWORD: admin
          CYPRESS_CUSTOMER_EMAIL: test@test.nl
          CYPRESS_CUSTOMER_PASSWORD: test

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .